sudo: false
language: node_js
before_deploy:
- npm-prepublish --verbose
deploy:
  provider: npm
  email: strategic.products@ft.com
  api_key:
    secure: oTr1Wxzg0ZHwc5Q3hP6D4D5eYrqksdh0a4lbeDs/y/YoQ89JLwCYgBbbhb5QUQb2Qm6YBnOEpy0b2ic/T/yHom0LcpxOz1OMfgWQrvB2fbL404AObRaXZHqQUx1FOoscSUFNVWKvrx7w6NSbML/Hdku4w62HH+DBeLx/2Wed+jfSMaofD0uYC5ck0PEmad2nIiA7t7EbQISwlbbZ17reoia8wNs7+eBjUqZCvuPeI19If4EDahkWyYLeGOUaW6r0aqPruFsf5kixY7sB2hlK6r3lEFCRMDIZVcyD8YxVEQiPHBxF77ygbTmM3au/5NsfaRZ7PAClrkyLRtZDf8WTPbbcgDS+AYr9p1B9W0DPzeCxdr1yIxnwwHDySLWWgw+l3hmRREX/dmOAxxpZSqLe0UUVAAMWXs5kRQik/A5stgWg0UbLtlkoqJzdw+SBm5z8dXsxUsFt8ZxUAtcIMzRG+Nl1V6iOZYdxsFuG+oGVV8UJBDUsSEumvgYoJBn9NcdDoCyJu0i0yYTXvJ2hC+sISr8TSJ/CKgZDCeQkktNajxZ2gFqSktMw7gKHTut0VusyXogP3ViVeOgz/F+TcLsgrb4zeaBUka1XGwDb0fmCwYREgoDUAs0GIY728ywfgD+c44Tr+hmIHP2XKV/f3cSW+kAGDv9kA/pQQ41iYXEBilc=
  on:
    tags: true
    repo: Financial-Times/perpage
